[[redirects]]
from = "https://deploy-preview-3--spruceid.netlify.app/*"
to = "http://75.2.70.75/:splat"
[redirects.headers]
Host = "www.spruceid.com"
status = 200

[[redirects]]
from = "/*"
to = "https://www.spruceid.com/:splat"
status = 301
