[[redirects]]
from = "https://deploy-preview-3--spruceid.netlify.app/*"
to = "https://rust.didkit.dev/:splat"
status = 200

[[redirects]]
from = "/*"
to = "https://www.spruceid.com/:splat"
status = 301
